spring.datasource.url=jdbc:mysql://localhost:3306/ride_hailing_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root

spring.datasource.password=Himanshu@709090
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update